---
- name: Install and configure nginx
  hosts: all
  become: true

  vars:
    nginx_port: 8080

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
      notify: Start nginx

    - name: Configure nginx from template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload nginx

    - name: Ensure nginx is enabled and started
      systemd:
        name: nginx
        enabled: true
        state: started

  handlers:
    - name: Start nginx
      systemd:
        name: nginx
        state: started

    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded
